/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonGroupOfTitleBar: typeof import('./src/components/ButtonGroupOfTitleBar.vue')['default']
    IHugeiconsArrowLeft01: typeof import('~icons/hugeicons/arrow-left01')['default']
    IHugeiconsArrowLeft02: typeof import('~icons/hugeicons/arrow-left02')['default']
    IHugeiconsArrowRight01: typeof import('~icons/hugeicons/arrow-right01')['default']
    IHugeiconsArrowRight02: typeof import('~icons/hugeicons/arrow-right02')['default']
    IHugeiconsArrowShrink: typeof import('~icons/hugeicons/arrow-shrink')['default']
    IHugeiconsBrowser: typeof import('~icons/hugeicons/browser')['default']
    IHugeiconsCancel01: typeof import('~icons/hugeicons/cancel01')['default']
    IHugeiconsCircleArrowDown01: typeof import('~icons/hugeicons/circle-arrow-down01')['default']
    IHugeiconsCodeSimple: typeof import('~icons/hugeicons/code-simple')['default']
    IHugeiconsConnect: typeof import('~icons/hugeicons/connect')['default']
    IHugeiconsDelete02: typeof import('~icons/hugeicons/delete02')['default']
    IHugeiconsFullScreen: typeof import('~icons/hugeicons/full-screen')['default']
    IHugeiconsMapPin: typeof import('~icons/hugeicons/map-pin')['default']
    IHugeiconsMinusSign: typeof import('~icons/hugeicons/minus-sign')['default']
    IHugeiconsPencil: typeof import('~icons/hugeicons/pencil')['default']
    IHugeiconsRefresh01: typeof import('~icons/hugeicons/refresh01')['default']
    IHugeiconsRefresh04: typeof import('~icons/hugeicons/refresh04')['default']
    IHugeiconsSourceCode: typeof import('~icons/hugeicons/source-code')['default']
    IHugeiconsTarget01: typeof import('~icons/hugeicons/target01')['default']
    IHugeiconsUserGroup: typeof import('~icons/hugeicons/user-group')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBarOfWindow: typeof import('./src/components/TitleBarOfWindow.vue')['default']
  }
}
