/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHugeiconsArrowShrink: typeof import('~icons/hugeicons/arrow-shrink')['default']
    IHugeiconsCancel01: typeof import('~icons/hugeicons/cancel01')['default']
    IHugeiconsCodeSimple: typeof import('~icons/hugeicons/code-simple')['default']
    IHugeiconsFullScreen: typeof import('~icons/hugeicons/full-screen')['default']
    IHugeiconsMi: typeof import('~icons/hugeicons/mi')['default']
    IHugeiconsMinusSign: typeof import('~icons/hugeicons/minus-sign')['default']
    IHugeiconsSourceCode: typeof import('~icons/hugeicons/source-code')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
