/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IHugeiconsArrowShrink: typeof import('~icons/hugeicons/arrow-shrink')['default']
    IHugeiconsCancel01: typeof import('~icons/hugeicons/cancel01')['default']
    IHugeiconsCodeSimple: typeof import('~icons/hugeicons/code-simple')['default']
    IHugeiconsFullScreen: typeof import('~icons/hugeicons/full-screen')['default']
    IHugeiconsMi: typeof import('~icons/hugeicons/mi')['default']
    IHugeiconsMinusSign: typeof import('~icons/hugeicons/minus-sign')['default']
    IHugeiconsSourceCode: typeof import('~icons/hugeicons/source-code')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const IHugeiconsArrowShrink: typeof import('~icons/hugeicons/arrow-shrink')['default']
  const IHugeiconsCancel01: typeof import('~icons/hugeicons/cancel01')['default']
  const IHugeiconsCodeSimple: typeof import('~icons/hugeicons/code-simple')['default']
  const IHugeiconsFullScreen: typeof import('~icons/hugeicons/full-screen')['default']
  const IHugeiconsMi: typeof import('~icons/hugeicons/mi')['default']
  const IHugeiconsMinusSign: typeof import('~icons/hugeicons/minus-sign')['default']
  const IHugeiconsSourceCode: typeof import('~icons/hugeicons/source-code')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NFlex: typeof import('naive-ui')['NFlex']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NH1: typeof import('naive-ui')['NH1']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NSpace: typeof import('naive-ui')['NSpace']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}