# 全局基础配置（所有服务共用）
DEBUG: false

# 通用 RabbitMQ 配置（可被消费端专属配置覆盖）
RABBITMQ:
  HOST: "47.238.5.253"
  PORT: 8803
  USERNAME: "infound.stg"
  PASSWORD: "xy6Ucz5IZ@Z%P)"
  VHOST: "/infound.stg"
  PREFETCH_COUNT: 1
  RECONNECT_DELAY: 5
  MAX_RECONNECT_ATTEMPTS: 1
  EXCHANGE_NAME: "chatbot.topic"
  ROUTING_KEY: "chatbot.sample"
  QUEUE_NAME: "chatbot.sample.queue.topic"
