# 全局基础配置（所有服务共用）
APP_NAME: "infound-backend-service"
DEBUG: true
HOST: "0.0.0.0"

# JWT 基础配置
JWT:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

# MySQL 基础配置
MYSQL:
  HOST: "47.238.5.253"
  PORT: 8801
  DB: "infound.stg"
  USER: "infound-stg"
  PASSWORD: "&3$BSW)mGxE(Zk"


# Redis 基础配置
REDIS:
  HOST: "47.238.5.253"
  PORT: 8802
  PASSWORD: "gcc+tvKgtjd&n_^@"
  DB: 0
  PREFIX: "if.dev"

# 日志基础配置
LOG:
  LEVEL: "INFO"
  DIR: "logs"
  FILE_MAX_SIZE: 10  # MB
  FILE_BACKUP_COUNT: 30  # 保留30天

# 跨域基础配置
CORS:
  ALLOW_ORIGINS:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  ALLOW_CREDENTIALS: true

# 通用业务配置
COMMON_TIMEOUT: 30
MAX_REQUEST_SIZE: 10485760  # 10MB

# RabbitMQ 配置
RABBITMQ:
  HOST: "47.238.5.253"
  PORT: 8803
  USERNAME: "infound.pro"
  PASSWORD: "Fwur5r1R#%I9+2a"
  VHOST: "/infound.pro"
  PREFETCH_COUNT: 1
  RECONNECT_DELAY: 5
  MAX_RECONNECT_ATTEMPTS: 1

  EXCHANGE_NAME: "chatbot.topic"
  QUEUE_NAME: "chatbot.sample.queue.topic"
  ROUTING_KEY_PREFIX: "chatbot.sample"

  OUTREACH_QUEUE: "chatbot.outreach.queue.topic"
  OUTREACH_ROUTING_KEY_PREFIX: "chatbot.outreach"
  OUTREACH_QUEUE_PREFIX: "chatbot.outreach.queue"
  OUTREACH_CONTROL_QUEUE: "chatbot.outreach.control.queue"
  OUTREACH_CONTROL_ROUTING_KEY_PREFIX: "chatbot.outreach.control"

  CRAWLER_EXCHANGE: "crawler.direct"
  CRAWLER_ROUTING_KEY: "crawler.tiktok.creator.key"
  CRAWLER_QUEUE: "crawler.tiktok.creator.queue"
